= OpenAPI Spring WebFlux Sample
:page-layout: default
:oap-spring: https://hauner.github.io/openapi-processor-spring
:oap-spring-webflux-sample: https://hauner.github.io/openapi-processor-spring-webflux-sample
:oap-json: https://hauner.github.io/openapi-processor-json
:oap-gradle: https://github.com/hauner/openapi-processor-gradle

//
// content
//

This is a simple Spring Boot (gradle) project that is using

* xref:spring:ROOT:index.adoc[openapi-processor-spring] to
generate java interfaces for the api defined in an openapi.yaml file
* link:{oap-json}[openapi-processor-json] to convert the openapi yaml to json format
* link:{oap-gradle}[openapi-processor-gradle] plugin to run both processors

The purpose of the sample is to show the setup of the gradle plugin, and the processors for an
**annotation** based Spring WebFlux application.

== Running the sample

Clone the project from link:{oap-spring-webflux-sample}[GitHub], navigate into the project root
folder and run

----
 ./gradlew bootRun
----

to start the sample application.


== Sample Endpoints

the sample has a few simple endpoints described with OpenAPI in `src/api`.

=== get all books

    curl http://localhost:8080/books

=== get single book

    curl http://localhost:8080/books/1

=== post new books

    curl --header "Content-Type: application/json" --data '[{"title":"Test Driven Development","authors":["Kent Beck"]}, {"title":"Growing Object-Oriented Software","authors":["Steve Freeman", "Nat Pryce"]}]' http://localhost:8080/books

